import {NavBar} from "@/components/NavBar";
import "@/styles/styles.scss"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <div className={"page-with-navbar"}>
            {children}
        </div>
      </body>
    </html>
  )
}
